databases:
  - name: cardmonkey_postgres
    databaseName: cardmonkey_production
    user: cardmonkey
    plan: starter

services:
  - type: web
    name: cardmonkey
    env: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    nodeVersion: 16.20.0
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cardmonkey_postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: NODE_ENV
        value: production
      - key: TAILWIND_MODE
        value: build
      - key: SMTP_ADDRESS
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
    healthCheckPath: /
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
