services:
  - type: web
    name: cardmonkey
    env: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    nodeVersion: 16.20.0
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        value: postgresql://godeck_database_user:OtDf5gcKXVUDjkpjkstAIrgE1yQEgKif@dpg-cu5pmm0gph6c73bvnn7g-a.frankfurt-postgres.render.com/godeck_database
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: NODE_ENV
        value: production
      - key: TAILWIND_MODE
        value: build
      - key: SMTP_ADDRESS
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
    healthCheckPath: /
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
